### PR TITLE
Handle case where component is null

### PR DESCRIPTION
**Pull request by liouh**
Didn't come up in my test scenario, but best to be safe.

### CODE REVIEW

**Comment by seanadkinson** [comment]
Hmm, I think the provided `component` would always be the current proxy component.  Not sure it would ever be null, since otherwise it wouldn't be transitioning away from it.

**Comment by liouh** [comment]
Not a common case, but I did get a null component when redirecting with this.replaceState() in componentWillMount. Came across it when trying workarounds for not being able to use renderUnavailable -- will open a separate discussion for that when I have enough info.

**Comment by seanadkinson** [comment]
We hit this in a certain case as well.  I think if the user is leaving before the component finished loading or something.  I'll go ahead and merge.

**Comment by seanadkinson** [comment]
Pushed `0.2.3`

**Pull request merged**
