### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by mikayel**
Version bump for react-router

### CODE REVIEW

**Comment by mikayel** [comment]
For avoiding npm install warnings.
I have tested here https://github.com/mikayel/react-cv and it is fine.

**Comment by seanadkinson** [comment]
No other changes needed to support `2.x`?  Nice.

Let's bump to `0.5` for this change though, since someone upgrading this library by a minor version bump shouldn't have to upgrade react-router by a major version.

Can you change this to `0.5.0`, confirm nothing needs to change for `react-router@2.x`, and then I'll merge and release?  Thanks!

**Comment by mikayel** [comment]
I have made the changes.

**Comment by seanadkinson** [comment]
Thanks

**Comment by seanadkinson** [comment]
Pushed `v0.5.0`

**Pull request merged**
